# Generated by Django 5.1.2 on 2024-10-25 05:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Digite um número de telefone válido.', regex='^\\+?1?\\d{9,15}$')])),
                ('endereco', models.CharField(max_length=255)),
                ('dados_pessoais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='gerenciadorDeCurriculos.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='gerenciadorDeCurriculos.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacao', to='gerenciadorDeCurriculos.dadospessoais')),
            ],
        ),
    ]
