# Generated by Django 5.1.2 on 2024-10-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciadorDeCurriculos', '0002_remove_contato_dados_pessoais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='dados_pessoais',
        ),
    ]
