# Generated by Django 5.1.2 on 2024-10-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciadorDeCurriculos', '0003_remove_experienciaprofissional_dados_pessoais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacaoacademica',
            name='dados_pessoais',
        ),
    ]
